
import static java.awt.SystemColor.menu;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Vaishnavi Chavan
 */
public class Homepage extends javax.swing.JFrame {

    /**
     * Creates new form Homepage
     */
    public Homepage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        menuBar1 = new java.awt.MenuBar();
        menu1 = new java.awt.Menu();
        menu2 = new java.awt.Menu();
        jLabel2 = new javax.swing.JLabel();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        jMenuBar2 = new javax.swing.JMenuBar();
        Product = new javax.swing.JMenu();
        Customer = new javax.swing.JMenu();
        Supplier = new javax.swing.JMenu();
        Purchased = new javax.swing.JMenu();
        Selled = new javax.swing.JMenu();
        Available = new javax.swing.JMenu();
        Report = new javax.swing.JMenu();
        RProduct = new javax.swing.JMenu();
        RSupplier = new javax.swing.JMenu();
        RCustomer = new javax.swing.JMenu();
        logoutMenu = new javax.swing.JMenu();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jMenuItem1.setText("jMenuItem1");

        menu1.setLabel("File");
        menuBar1.add(menu1);

        menu2.setLabel("Edit");
        menuBar1.add(menu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("HomePage");
        setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        setMinimumSize(new java.awt.Dimension(1920, 1080));
        setSize(new java.awt.Dimension(1920, 1080));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/n2.jpg"))); // NOI18N

        jInternalFrame1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jInternalFrame1.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jInternalFrame1.setVisible(true);

        jMenuBar2.setBackground(new java.awt.Color(204, 204, 255));
        jMenuBar2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jMenuBar2.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jMenuBar2.setPreferredSize(new java.awt.Dimension(1920, 32));
        jMenuBar2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jMenuBar2FocusGained(evt);
            }
        });
        jMenuBar2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuBar2MouseClicked(evt);
            }
        });

        Product.setBorder(new javax.swing.border.MatteBorder(null));
        Product.setForeground(new java.awt.Color(51, 0, 51));
        Product.setText("Product");
        Product.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        Product.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Product.setPreferredSize(new java.awt.Dimension(100, 30));
        Product.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ProductMouseClicked(evt);
            }
        });
        jMenuBar2.add(Product);

        Customer.setBorder(new javax.swing.border.MatteBorder(null));
        Customer.setForeground(new java.awt.Color(51, 0, 51));
        Customer.setText("Customers");
        Customer.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        Customer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Customer.setPreferredSize(new java.awt.Dimension(100, 30));
        Customer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CustomerMouseClicked(evt);
            }
        });
        jMenuBar2.add(Customer);

        Supplier.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Supplier.setForeground(new java.awt.Color(51, 0, 51));
        Supplier.setText("Suppliers");
        Supplier.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        Supplier.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Supplier.setPreferredSize(new java.awt.Dimension(100, 30));
        Supplier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SupplierMouseClicked(evt);
            }
        });
        jMenuBar2.add(Supplier);

        Purchased.setBorder(new javax.swing.border.MatteBorder(null));
        Purchased.setForeground(new java.awt.Color(51, 0, 51));
        Purchased.setText("Purchased");
        Purchased.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        Purchased.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Purchased.setPreferredSize(new java.awt.Dimension(100, 30));
        Purchased.addMenuKeyListener(new javax.swing.event.MenuKeyListener() {
            public void menuKeyPressed(javax.swing.event.MenuKeyEvent evt) {
                PurchasedMenuKeyPressed(evt);
            }
            public void menuKeyReleased(javax.swing.event.MenuKeyEvent evt) {
            }
            public void menuKeyTyped(javax.swing.event.MenuKeyEvent evt) {
            }
        });
        Purchased.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                PurchasedMenuSelected(evt);
            }
        });
        Purchased.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PurchasedMouseClicked(evt);
            }
        });
        jMenuBar2.add(Purchased);

        Selled.setBorder(new javax.swing.border.MatteBorder(null));
        Selled.setForeground(new java.awt.Color(51, 0, 51));
        Selled.setText("Sold");
        Selled.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        Selled.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Selled.setPreferredSize(new java.awt.Dimension(100, 30));
        Selled.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SelledMouseClicked(evt);
            }
        });
        jMenuBar2.add(Selled);

        Available.setBorder(new javax.swing.border.MatteBorder(null));
        Available.setForeground(new java.awt.Color(51, 0, 51));
        Available.setText("Available");
        Available.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        Available.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Available.setPreferredSize(new java.awt.Dimension(100, 30));
        Available.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AvailableMouseClicked(evt);
            }
        });
        jMenuBar2.add(Available);

        Report.setBorder(new javax.swing.border.MatteBorder(null));
        Report.setForeground(new java.awt.Color(51, 0, 51));
        Report.setText("Report");
        Report.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        Report.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Report.setPreferredSize(new java.awt.Dimension(100, 30));
        Report.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ReportMouseClicked(evt);
            }
        });

        RProduct.setText("Product ");
        RProduct.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        RProduct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RProductMouseClicked(evt);
            }
        });
        Report.add(RProduct);

        RSupplier.setText("Supplier");
        RSupplier.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        RSupplier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RSupplierMouseClicked(evt);
            }
        });
        Report.add(RSupplier);

        RCustomer.setText("Customer");
        RCustomer.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        RCustomer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RCustomerMouseClicked(evt);
            }
        });
        Report.add(RCustomer);

        jMenuBar2.add(Report);

        logoutMenu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        logoutMenu.setText("Log Out");
        logoutMenu.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        logoutMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMenuMouseClicked(evt);
            }
        });
        jMenuBar2.add(logoutMenu);

        jInternalFrame1.setJMenuBar(jMenuBar2);
        jMenuBar2.getAccessibleContext().setAccessibleName("menu");
        jMenuBar2.getAccessibleContext().setAccessibleParent(jInternalFrame1);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1920, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 4, Short.MAX_VALUE)
        );

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/n6.jpg"))); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/M3.png"))); // NOI18N

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/M5.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addGap(0, 0, 0)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addContainerGap(210, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuBar2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuBar2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuBar2MouseClicked

    private void jMenuBar2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jMenuBar2FocusGained
         //TODO add your handling code here:
      //  menu.getGreen();
    }//GEN-LAST:event_jMenuBar2FocusGained

    private void logoutMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMenuMouseClicked
        // TODO add your handling code here:
        int response=JOptionPane.showConfirmDialog(this,"Are you sure to Exit ?", "LOG OUT",  JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if(response==JOptionPane.YES_OPTION)
        {
//             Login_Page lh=new Login_Page();
//            lh.setVisible(true);
            System.exit(0);
        }
       
    }//GEN-LAST:event_logoutMenuMouseClicked

    private void ProductMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProductMouseClicked
        // TODO add your handling code here:
        Add_Product ap=new Add_Product();
        ap.show();
    }//GEN-LAST:event_ProductMouseClicked

    private void SupplierMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SupplierMouseClicked
        // TODO add your handling code here:
        Suppliers sr=new Suppliers();
        sr.show();
    }//GEN-LAST:event_SupplierMouseClicked

    private void CustomerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CustomerMouseClicked
        // TODO add your handling code here:
        Customers cr=new Customers();
        cr.show();
    }//GEN-LAST:event_CustomerMouseClicked

    private void ReportMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ReportMouseClicked
        // TODO add your handling code here:
        //        Report nr=new Report();
        //        nr.show();
    }//GEN-LAST:event_ReportMouseClicked

    private void RCustomerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RCustomerMouseClicked
        // TODO add your handling code here:
        Customer_Report cr=new Customer_Report();
        cr.show();
    }//GEN-LAST:event_RCustomerMouseClicked

    private void RSupplierMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RSupplierMouseClicked
        // TODO add your handling code here:

        Supplier_Report sr=new Supplier_Report();
        sr.show();
    }//GEN-LAST:event_RSupplierMouseClicked

    private void RProductMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RProductMouseClicked
        // TODO add your handling code here:
        Report nr=new Report();
        nr.show();
    }//GEN-LAST:event_RProductMouseClicked

    private void AvailableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AvailableMouseClicked
        // TODO add your handling code here:
        Available ab=new Available();
        ab.show();
    }//GEN-LAST:event_AvailableMouseClicked

    private void SelledMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SelledMouseClicked
        // TODO add your handling code here:
        Selled sd=new Selled();
        sd.show();
    }//GEN-LAST:event_SelledMouseClicked

    private void PurchasedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PurchasedMouseClicked
        // TODO add your handling code here:
        Purchased pt=new Purchased();
        pt.show();
    }//GEN-LAST:event_PurchasedMouseClicked

    private void PurchasedMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_PurchasedMenuSelected
        // TODO add your handling code here:
    }//GEN-LAST:event_PurchasedMenuSelected

    private void PurchasedMenuKeyPressed(javax.swing.event.MenuKeyEvent evt) {//GEN-FIRST:event_PurchasedMenuKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_PurchasedMenuKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Homepage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Available;
    private javax.swing.JMenu Customer;
    private javax.swing.JMenu Product;
    private javax.swing.JMenu Purchased;
    private javax.swing.JMenu RCustomer;
    private javax.swing.JMenu RProduct;
    private javax.swing.JMenu RSupplier;
    private javax.swing.JMenu Report;
    private javax.swing.JMenu Selled;
    private javax.swing.JMenu Supplier;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JMenu logoutMenu;
    private java.awt.Menu menu1;
    private java.awt.Menu menu2;
    private java.awt.MenuBar menuBar1;
    // End of variables declaration//GEN-END:variables
}
